### PR TITLE
Implement Thing object type

### PR DESCRIPTION
**Pull request by Vesihiisi**
See https://github.com/NordicMuseum/Wikimedia-Commons-uploads/issues/20

### CODE REVIEW

**Comment by Vesihiisi** [comment]
obs. implement otherInformation

**Comment by Vesihiisi** [comment]
~~otherInformation is Harvested, but not implemented in makeinfo yet...~~

added as part of original_desc

**Comment by Ambrosiani** [comment]
perhaps name related images starting with 1 instead of 0?

(i.e. so that https://commons.wikimedia.org/wiki/File:Damhatt_dekorerad_med_ceriserosa_fjädrar_över_hela_kullen_-_Nordiska_museet_-_NM.0332401_(0).jpg ends with "(1).jpg" instead)

**Comment by Vesihiisi** [comment]
Right, that's how normal people count, I've heard ;)

**Comment by Vesihiisi** [comment]
note to self: overwrite the slider no immediately when loading the json, that should trickle down to all the relevant places....

**Comment by Vesihiisi** [comment]
after that i'll probably merge this pr since it's The Big Thing That Technically Works Now 🎆

**Pull request merged**
